VERBFORMEN_URL = "https://www.verbformen.ru/"
VERBFORMEN_WORD_CLASSES = (
    "vGrnd rCntr"
)
VERBFORMEN_WORD_VERB_CLASSES = (
    "vGrnd rCntr rClear"
)
VERBFORMEN_TRANSLATIONS_CLASSES = (
    "r1Zeile rU3px rO0px"
)
VERBFORMEN_NAV_CLASS = (
    "rKrml rKln rInf"
)
AMOUNT_OF_GRAMMATICAL_CASES = 4
NOUNS_WRAPPER_CLASS = (
    "vDkl"
)
NOUNS_TABLE_CLASS = (
    "vTbl"
)

STRONG_DECLENSION_INDEX = 1
WEAK_DECLENSION_INDEX = 2
MIXED_DECLENSION_INDEX = 3

DECLENSION_TABLE_CLASS = (
    "vTbl"
)